language: php

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake
    - libgnutls-dev
    - libuuid1
    - uuid
    - uuid-dev

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - build

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
    global:
      - TASKWARRIOR=2.5.1
      - GCC_VERSION=5
      - CXX="g++-5"
      - CC="gcc-5"
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""
      - TASKWARRIOR=2.5.0

matrix:
  allow_failures:
      - php: hhvm

install:
  - gcc -v
  - bash build.sh $TASKWARRIOR
  - chmod +x build/taskwarrior-$TASKWARRIOR
  - ln -s build/taskwarrior-$TASKWARRIOR task
  - ./task --version

before_script:
    - composer self-update
    - composer update $PREFER_LOWEST

script:
  - vendor/bin/phpunit
