language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

env:
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

before_install:
  - wget http://taskwarrior.org/download/task-2.4.3.tar.gz
  - gunzip task-2.4.3.tar.gz
  - tar xf task-2.4.3.tar
  - cd task-2.4.3
  - sudo apt-get install cmake build-essential uuid-dev libgnutls-dev libreadline6-dev --force-yes
  - sudo cmake -DCMAKE_BUILD_TYPE=release .
  - sudo make
  - sudo make install
  - sudo ln -s /usr/local/bin/task /usr/bin/task
  - task --version
  - cd ..

before_script:
    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST

matrix:
  allow_failures:
    - php: 7
    - php: nightly
    - php: hhvm
