language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install: make get-deps

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
    global:
      - TASKWARRIOR=2.5.0
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

matrix:
  allow_failures:
      - php: 7
      - php: hhvm

before_install:
  - composer self-update

install:
  - ln -s build/taskwarrior-$TASKWARRIOR task
  - chmod +x ./task
  - ./task --version

before_script:
    - composer update $PREFER_LOWEST

