language: php

addons:
  apt:
    packages:
    - cmake
    - libgnutls-dev
    - libuuid1
    - uuid
    - uuid-dev

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - build

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
    global:
      - TASKWARRIOR=2.4.4
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

matrix:
  include:
      - php: 5.6
        env: TASKWARRIOR=2.4.3
      - php: 5.6
        env: TASKWARRIOR=2.5.0
  allow_failures:
      - php: 7
      - php: hhvm
      - php: 5.6
        env: TASKWARRIOR=2.5.0

install:
  - bash build.sh $TASKWARRIOR
  - ln -s build/taskwarrior-$TASKWARRIOR task
  - chmod +x ./task
  - ./task --version

before_script:
    - composer self-update
    - composer update $PREFER_LOWEST

script:
  - vendor/bin/phpunit