language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm
  - hhvm-nightly

env:
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

before_install:
  - sudo add-apt-repository ppa:ultrafredde/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq task --force-yes
  - task --version

before_script:
    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST

matrix:
  allow_failures:
    - php: 7
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
